name: Build

on:
  # push:
  #   paths:
  #     - "configs/**"
  #     - ".github/workflows/build-openwrt.yml"
  #     - "scripts/openwrt/**"
  #   branches-ignore:
  #     - stable
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH"
        required: false
        default: ""
      ssh_quick:
        description: "Quick SSH"
        required: false
        default: ""

  repository_dispatch:
    types: [trigger-build]

env:
  SOURCE_URL: https://github.com/coolsnowwolf/lede
  SOURCE_BRANCH: master
  TOOLCHAIN_TAG: Toolchain
  SOURCE: lede
  TZ: Asia/Shanghai
  APP_CONFIG: configs/app.config
  WEB_BRANCH: web
  WEB_PATH: web

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: set-matrix
        run: |
          # Change directory to configs
          cd configs
          # Initialize the matrix variable
          matrix="{\"include\":["

          # Loop through each folder in the configs directory
          for d in */ ; do
              # Remove the trailing slash from the folder name
              device_name=${d%/}
              # Append the device name to the matrix variable
              matrix="$matrix{\"device\":\"$device_name\"},"
          done

          # Remove the trailing comma from the matrix variable
          matrix=${matrix%,}
          # Close the matrix variable
          matrix="$matrix]}"
          # Change back to the previous directory
          cd ..
          # Set the matrix output
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo $matrix

  Toolchain:
    needs: generate-matrix

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    runs-on: ubuntu-latest

    outputs:
      OPENWRT_PATH: ${{ steps.clone.outputs.OPENWRT_PATH }}
      VERSION_INFO: ${{ steps.clone.outputs.VERSION_INFO }}
      CURRENT_BRANCH: ${{ steps.env.outputs.CURRENT_BRANCH }}
      SOURCE_REPO: ${{ steps.env.outputs.SOURCE_REPO }}
      DEVICE_TARGET: ${{ steps.env.outputs.DEVICE_TARGET }}
      DEVICE_SUBTARGET: ${{ steps.env.outputs.DEVICE_SUBTARGET }}
      TOOLCHAIN_IMAGE: ${{ steps.env.outputs.TOOLCHAIN_IMAGE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 初始化环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL is.gd/depends_ubuntu_2204)
          sudo -E apt-get -qq install aria2 clang clangd ecj lib32gcc-s1 libfuse-dev libncursesw5 \
                                  libpython3-dev lld lldb python3-ply re2c
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"

      - name: 克隆源码
        id: clone
        run: |
          df -hT $GITHUB_WORKSPACE
          git clone $SOURCE_URL -b $SOURCE_BRANCH openwrt
          cd openwrt
          echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
          echo "OPENWRT_PATH=$(echo $PWD)" >> $GITHUB_OUTPUT
          export VERSION_INFO=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H")
          echo "VERSION_INFO=$VERSION_INFO" >> $GITHUB_ENV
          echo "VERSION_INFO=$(echo $VERSION_INFO)" >> $GITHUB_OUTPUT

      - name: 生成Toolchain配置
        run: |

          mv configs/${{ matrix.Device }}/.config $OPENWRT_PATH/.config
          cat $GITHUB_WORKSPACE/$APP_CONFIG >> $OPENWRT_PATH/.config
          cd $OPENWRT_PATH && make defconfig
          sed -i '/CONFIG_DEFAULT_luci/'d .config

          echo -e "\nCONFIG_ALL=y" >> $OPENWRT_PATH/.config
          echo -e "\nCONFIG_ALL_NONSHARED=y" >> $OPENWRT_PATH/.config
          cd $OPENWRT_PATH
          make defconfig > /dev/null 2>&1

      - name: 生成变量
        id: env
        run: |
          export CURRENT_BRANCH="$(git symbolic-ref --short HEAD)"
          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
          echo "CURRENT_BRANCH=$(echo $CURRENT_BRANCH)" >> $GITHUB_OUTPUT
          cd $OPENWRT_PATH
          export SOURCE_REPO="$(echo $SOURCE_URL | awk -F '/' '{print $(NF)}')"
          echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
          echo "SOURCE_REPO=$(echo $SOURCE_REPO)" >> $GITHUB_OUTPUT
          export DEVICE_TARGET=$(cat .config | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}')
          echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
          echo "DEVICE_TARGET=$(echo $DEVICE_TARGET)" >> $GITHUB_OUTPUT
          export DEVICE_SUBTARGET=$(cat .config | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}')
          echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
          echo "DEVICE_SUBTARGET=$(echo $DEVICE_SUBTARGET)" >> $GITHUB_OUTPUT
          export TOOLCHAIN_IMAGE="toolchain-$SOURCE_REPO-$SOURCE_BRANCH-${{ matrix.Device }}"
          echo "TOOLCHAIN_IMAGE=$TOOLCHAIN_IMAGE" >> $GITHUB_ENV
          echo "TOOLCHAIN_IMAGE=$(echo $TOOLCHAIN_IMAGE)" >> $GITHUB_OUTPUT

      - name: 比较Toolchain Hash
        id: hash
        run: |
          cd $OPENWRT_PATH
          export CURRENT_HASH=$(git log --pretty=tformat:"%H" -n1 tools toolchain)
          echo "CURRENT_HASH=$CURRENT_HASH" >> $GITHUB_ENV
          echo "CURRENT_HASH is $CURRENT_HASH"
          export CACHE_HASH=$(curl -fSsL -k https://github.com/$GITHUB_REPOSITORY/releases/download/$TOOLCHAIN_TAG/$TOOLCHAIN_IMAGE.hash)
          echo "CACHE_HASH is $CACHE_HASH"
          if [ -z "$CACHE_HASH" ] || [ "$CURRENT_HASH" != "$CACHE_HASH" ]; then
            echo "REBUILD_TOOLCHAIN=true" >> $GITHUB_OUTPUT
          fi

      - name: 安装Feeds
        if: steps.hash.outputs.REBUILD_TOOLCHAIN == 'true'
        run: |
          cd $OPENWRT_PATH
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 编译Tools
        if: steps.hash.outputs.REBUILD_TOOLCHAIN == 'true'
        run: |
          cd $OPENWRT_PATH
          make defconfig
          echo -e "$(nproc) thread compile"
          make tools/compile -j$(nproc) || make tools/compile -j1 V=s

      - name: 编译Toolchain
        if: steps.hash.outputs.REBUILD_TOOLCHAIN == 'true'
        run: |
          cd $OPENWRT_PATH
          echo -e "$(nproc) thread compile"
          make toolchain/compile -j$(nproc) || make toolchain/compile -j1 V=s
          rm -rf .config* dl bin

      - name: 生成Toolchain Image
        if: steps.hash.outputs.REBUILD_TOOLCHAIN == 'true'
        run: |

          mksquashfs openwrt $TOOLCHAIN_IMAGE -force-gid 1001 -force-uid 1001 -comp zstd
          mkdir -p $GITHUB_WORKSPACE/output
          split -d -b 1900M $TOOLCHAIN_IMAGE $GITHUB_WORKSPACE/output/$TOOLCHAIN_IMAGE.img.
          rm $TOOLCHAIN_IMAGE
          echo $CURRENT_HASH > $GITHUB_WORKSPACE/output/$TOOLCHAIN_IMAGE.hash
          ls -lh $GITHUB_WORKSPACE/output

      - name: 上传Toolchain Image到Release
        if: steps.hash.outputs.REBUILD_TOOLCHAIN == 'true'
        uses: ncipollo/release-action@main
        with:
          name: Toolchain-Image
          allowUpdates: true
          replacesArtifacts: true
          tag: ${{ env.TOOLCHAIN_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: output/*
          body: OpenWrt 工具链镜像文件

  build:
    needs: [generate-matrix, Toolchain]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}

    env:
      OPENWRT_PATH: ${{ needs.Toolchain.outputs.OPENWRT_PATH }}
      VERSION_INFO: ${{ needs.Toolchain.outputs.VERSION_INFO }}
      CURRENT_BRANCH: ${{ needs.Toolchain.outputs.CURRENT_BRANCH }}
      SOURCE_REPO: ${{ needs.Toolchain.outputs.SOURCE_REPO }}

    steps:
      - name: 精简系统释放磁盘空间 (Ubuntu)
        uses: c3p7f2/free-disk-space@main
        with:
          tool-cache: true
          docker-images: false

      - name: 组合磁盘
        run: |
          export ROOT_FREE_KB=$(df --block-size=1024 --output=avail / | tail -1)
          export ROOT_LOOP_KB=$(expr $ROOT_FREE_KB - 1048576)
          export ROOT_LOOP_BYTES=$(expr $ROOT_LOOP_KB \* 1024)
          sudo fallocate -l $ROOT_LOOP_BYTES /root.img
          export ROOT_LOOP_DEVNAME=$(sudo losetup -Pf --show /root.img)
          sudo pvcreate -f $ROOT_LOOP_DEVNAME
          export MNT_FREE_KB=$(df --block-size=1024 --output=avail /mnt | tail -1)
          export MNT_LOOP_KB=$(expr $MNT_FREE_KB - 102400)
          export MNT_LOOP_BYTES=$(expr $MNT_LOOP_KB \* 1024)
          sudo fallocate -l $MNT_LOOP_BYTES /mnt/mnt.img
          export MNT_LOOP_DEVNAME=$(sudo losetup -Pf --show /mnt/mnt.img)
          sudo pvcreate -f $MNT_LOOP_DEVNAME
          sudo vgcreate vgstorage $ROOT_LOOP_DEVNAME $MNT_LOOP_DEVNAME
          sudo lvcreate -n lvstorage -l 100%FREE vgstorage
          export LV_DEVNAME=$(sudo lvscan | awk -F "'" '{print $2}')
          sudo mkfs.btrfs -L combinedisk $LV_DEVNAME
          sudo mount -o compress=zstd $LV_DEVNAME $GITHUB_WORKSPACE
          sudo chown -R runner:runner $GITHUB_WORKSPACE
          mkdir -p $GITHUB_WORKSPACE/tmp && chmod 777 $GITHUB_WORKSPACE/tmp
          sudo cp -rp /tmp/* $GITHUB_WORKSPACE/tmp
          sudo mount -B $GITHUB_WORKSPACE/tmp /tmp && df -hT

          # 这里挂载会影响到$GITHUB_WORKSPACE，不要在后续步骤挂载，最好在编译步骤开启就跑

      - name: SSH 下关闭其他工作流
        if: ${{ github.event_name == 'workflow_dispatch' && (inputs.ssh || inputs.ssh_quick)  && matrix.Device != 'x86' }}
        run: |
          sudo halt

      - name: ssh to action
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.ssh_quick  && contains(matrix.Device, 'x86')}}
        env:
          CLOUDFLARED_TOKEN: ${{ secrets.CLOUDFLARED_TOKEN }}
        run: |
          /bin/bash $GITHUB_WORKSPACE/scripts/ssh.sh

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"

          ulimit -u 10000
          ulimit -n 4096
          ulimit -d unlimited
          ulimit -m unlimited
          ulimit -s unlimited
          ulimit -t unlimited
          ulimit -v unlimited       
           
          sudo apt update -y
          sudo apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
          mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
          rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev python3-pyelftools
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Checkout
        run: |
          cd $GITHUB_WORKSPACE
          git init
          git remote add origin https://github.com/$GITHUB_REPOSITORY
          git fetch
          git checkout -t origin/$CURRENT_BRANCH

      - name: 准备Toolchain Image
        run: |

          for i in {0..9}
          do
            echo downloading..
            curl -fsL -k https://github.com/$GITHUB_REPOSITORY/releases/download/$TOOLCHAIN_TAG/toolchain-$SOURCE_REPO-$SOURCE_BRANCH-${{ matrix.Device }}.img.0$i >> toolchain-$SOURCE_REPO-$SOURCE_BRANCH-${{ matrix.Device }}.img || break
          done
          mkdir -p openwrt-ro openwrt workdir overlay
          sudo mount -o loop toolchain-$SOURCE_REPO-$SOURCE_BRANCH-${{ matrix.Device }}.img openwrt-ro
          sudo mount -t overlay overlay -o lowerdir=openwrt-ro,upperdir=overlay,workdir=workdir openwrt
          echo $GITHUB_WORKSPACE
          echo $OPENWRT_PATH
          cd $OPENWRT_PATH
          git pull

      - name: Add packages
        run: |
          cd $OPENWRT_PATH          
          chmod +x $GITHUB_WORKSPACE/scripts/openwrt/add-package.sh
          $GITHUB_WORKSPACE/scripts/openwrt/add-package.sh
          git pull
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Update configuration
        run: |
          cp $GITHUB_WORKSPACE/configs/${{ matrix.Device }}/.config $OPENWRT_PATH/.config
          cat $GITHUB_WORKSPACE/$APP_CONFIG >> $OPENWRT_PATH/.config
          cd $OPENWRT_PATH && make defconfig
          sed -i '/CONFIG_DEFAULT_luci/'d .config

      - name: echo openwrt config
        run: cat $OPENWRT_PATH/.config

      - name: echo plugins
        run: |
          cd $OPENWRT_PATH

          ## 输出LUCI-APP
          echo
          echo "=========================================="
          grep -i CONFIG_PACKAGE_luci-app .config | grep  -v \# > Plug-in
          grep -i CONFIG_PACKAGE_luci-theme .config | grep  -v \# >> Plug-in
          sed -i '/INCLUDE/d' Plug-in > /dev/null 2>&1
          sed -i 's/CONFIG_PACKAGE_/、/g' Plug-in
          sed -i '/qbittorrent_static/d' Plug-in > /dev/null 2>&1
          sed -i 's/=y/\ /g' Plug-in
          awk '$0=NR$0' Plug-in > Plug-2
          awk '{print "	" $0}' Plug-2 > Plug-in
          echo
          echo
          echo "	      已选插件列表"
          cat Plug-in
          rm -rf {Plug-in,Plug-2}
          echo
          echo "=========================================="

      - name: Make download
        run: |
          cd $OPENWRT_PATH
          make download -j8

      - name: 定制
        run: |
          cd $OPENWRT_PATH

          if [[ ${{ matrix.Device }} == *"x86"* ]]; then
            arch="amd64"
          else
            arch="arm64"
          fi
                  
          /bin/bash $GITHUB_WORKSPACE/scripts/openwrt/vektor-exec.sh $arch

          if [ -n "$(ls -A "$GITHUB_WORKSPACE/files" 2>/dev/null)" ]; then
           cp -Rf $GITHUB_WORKSPACE/files/* ./
          fi

      - name: ssh to action
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.ssh  && contains(matrix.Device, 'x86')}}
        env:
          CLOUDFLARED_TOKEN: ${{ secrets.CLOUDFLARED_TOKEN }}
        run: |
          /bin/bash $GITHUB_WORKSPACE/scripts/ssh.sh

      - name: 编译Packages
        id: compile
        run: |
          cd $OPENWRT_PATH
          echo -e "$(nproc) thread compile"
          make diffconfig
          make target/compile -j$(nproc) IGNORE_ERRORS="m n" BUILD_LOG=1 || \
          yes n | make target/compile -j1 V=s IGNORE_ERRORS=1
          make package/compile -j$(nproc) IGNORE_ERRORS=1 || make package/compile -j1 V=s IGNORE_ERRORS=1
          make package/index

      - name: 生成固件
        id: generate
        run: |
          cd $OPENWRT_PATH
          mkdir -p files/etc/uci-defaults
          cp $GITHUB_WORKSPACE/scripts/openwrt/init-settings.sh files/etc/uci-defaults/99-init-settings
          make package/install -j$(nproc)  || make package/install -j1 V=s
          make target/install -j$(nproc)  || make target/install -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          make json_overview_image_info
          make checksum

      - name: Organize files
        run: |

          cd $OPENWRT_PATH/bin/targets/*/*

          rm -rf \
          packages \
          sha256* \
          *manifest \
          *.sha \
          *info \
          *kernel.bin \
          *sha \
          *json

          echo "PACKAGED_OUTPUTPATH=$PWD" >> $GITHUB_ENV

      - name: Package Armvirt as OpenWrt
        if: contains(matrix.Device, 'n1')
        uses: ophub/flippy-openwrt-actions@main
        env:
          OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
          PACKAGE_SOC: s905d
          WHOAMI: Redstone

      - name: 生成变量
        run: |
          cd $OPENWRT_PATH

          useVersionInfo=$(git show -s --date=short --format="提交人: %an<br/>提交时间: %cd<br/>提交内容: %s<br/>提交哈希值: %H")
          echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV

          echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "release_tag=${{ env.CURRENT_BRANCH }}-$(date +'%Y.%m.%d')-download" >> $GITHUB_ENV
          echo "DEVICES=$(echo '${{ needs.generate-matrix.outputs.matrix }}' | jq -r '.include[].device' | tr '\n' ' ')" >> $GITHUB_ENV
          echo "WORKFLOW=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

          echo "BIN_PATH=openwrt/${{ matrix.Device }}/${{ env.CURRENT_BRANCH }}" >> $GITHUB_ENV

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "${{ env.CURRENT_BRANCH }} | 多平台固件下载集"
          tag_name: ${{ env.release_tag }}
          body: |
            **固件信息：**
            - 分支：${{ env.CURRENT_BRANCH }}
            - 编译日期：${{ env.DATE }}
            - 编译日志： ${{ env.WORKFLOW}}
            - 支持设备/平台：${{ env.DEVICES }}

            国内加速下载：https://js.7fan.fun/ https://ghproxy.com/ https://ghps.cc/

            **_Redstone | Powered by ${{ env.SOURCE_URL }} ${{ env.SOURCE_BRANCH }} branch_**
          files: ${{ env.PACKAGED_OUTPUTPATH }}/*

      - name: 提交固件
        run: |
          git checkout ${{env.WEB_BRANCH}}
          git pull

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          # the path that the root of web-branch
          git lfs install

          mkdir -p ${{env.BIN_PATH}}
          mv ${{ env.PACKAGED_OUTPUTPATH }}/* ${{env.BIN_PATH}}/
          git lfs track "${{env.BIN_PATH}}/*.gz"
          git add .gitattributes || echo 'Err, but continue.'
          git commit -m - || echo 'Err, but continue.'
          git push --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"  HEAD:$WEB_BRANCH || echo 'Err, but continue.'

          git add .
          git commit -m -
          git push --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$WEB_BRANCH

      - name: TG Notification - ❌
        if: ${{ !success() }}
        continue-on-error: true
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            编译失败 ❌

            设备/平台：${{ matrix.Device }}
            分支：${{ env.CURRENT_BRANCH }}

      - name: TG Notification - ✔️
        if: ${{ success() }}
        continue-on-error: true
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            编译成功 ✔️

            设备/平台：${{ matrix.Device }}
            分支：${{ env.CURRENT_BRANCH }}

            下载地址：https://github.com/${{ github.repository }}/releases/tag/${{ env.release_tag }}

      - uses: otto-de/purge-deprecated-workflow-runs@v2
        with:
          remove-failed: true
          remove-cancelled: true
          remove-skipped: true

      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 7
          delete_tag_pattern: download
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
